name: Christian Busse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94975
title: Portfolio Showcase
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7633e'
    - '#ffffff'
    - '#783e26'
    - '#cad93e'
    - '#1b1d04'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
